### ISSUE TITLE
Bonfire 0.7.3 : Cannot save site settings

### ISSUE THREAD

**Issue by kocil** [ci-bonfire/Bonfire#1118]
Dear bonfire developer.

I'm  just a first time user, so firstly, thanks for the job you have done.
I would like to report an issue.
I've installed bonfire 0.7.3, then migrated it to CI3 as instructed on the docs.
The problem was on the admin "Settings - Settings" menu,
"Site settings" form, "Site Information" tab.
I changed the "Site name", then pressed the "Save" button, 
but then the following error occured.
-------------------------------------
Error Number: 1048

Column 'value' cannot be null

UPDATE `bf_settings` SET `value` = CASE WHEN `name` = 'site.title' THEN 'My SITE' WHEN `name` = 'site.system_email' THEN 'admin@mybonfire.com' WHEN `name` = 'site.status' THEN '1' WHEN `name` = 'site.list_limit' THEN '25' WHEN `name` = 'auth.allow_register' THEN 1 WHEN `name` = 'auth.user_activation_method' THEN 0 WHEN `name` = 'auth.login_type' THEN 'email' WHEN `name` = 'auth.use_usernames' THEN '1' WHEN `name` = 'auth.allow_remember' THEN 1 WHEN `name` = 'auth.remember_length' THEN 1209600 WHEN `name` = 'auth.use_extended_profile' THEN 0 WHEN `name` = 'auth.allow_name_change' THEN 1 WHEN `name` = 'auth.name_change_frequency' THEN '1' WHEN `name` = 'auth.name_change_limit' THEN '1' WHEN `name` = 'auth.password_min_length' THEN '8' WHEN `name` = 'auth.password_force_numbers' THEN NULL WHEN `name` = 'auth.password_force_symbols' THEN NULL WHEN `name` = 'auth.password_force_mixed_case' THEN NULL WHEN `name` = 'auth.password_show_labels' THEN 0 WHEN `name` = 'password_iterations' THEN '8' WHEN `name` = 'site.show_profiler' THEN 1 WHEN `name` = 'site.show_front_profiler' THEN 1 WHEN `name` = 'site.languages' THEN 'a:3:{i:0;s:7:\"english\";i:1;s:7:\"persian\";i:2;s:10:\"portuguese\";}' ELSE `value` END WHERE `name` IN('site.title','site.system_email','site.status','site.list_limit','auth.allow_register','auth.user_activation_method','auth.login_type','auth.use_usernames','auth.allow_remember','auth.remember_length','auth.use_extended_profile','auth.allow_name_change','auth.name_change_frequency','auth.name_change_limit','auth.password_min_length','auth.password_force_numbers','auth.password_force_symbols','auth.password_force_mixed_case','auth.password_show_labels','password_iterations','site.show_profiler','site.show_front_profiler','site.languages')

Filename: /home/kocil/lampstack-5.5.25-0/frameworks/bonfire/bonfire/core/BF_Model.php

Line Number: 622
----------------------------

Additional system information:
OS : Ubuntu 14.04
LAMP STACK : bitnami lampstack-5.5.25
Bonfire Version : v0.7.3
CodeIgniter Version : 3.0.0
PHP Version : 5.5.25

Since this is my second days with CI and BF, I'm sorry that I have no clue regarding the error.
Thank you for your attention.
Best regard.

**Comment by mwhitneysdsu** [comment]
This was fixed in #1115, which was released in 0.7.4.

**Comment by Erreke** [comment]
In version 0.8.0, this error still occurs.
Sorry for my bad English.

**Comment by mwhitneysdsu** [comment]
Sorry, I was mistaken about what the issue actually was.

When any of the following checkboxes on the Security tab are unchecked, the above-mentioned error occurs: 
- Should password force numbers? (auth.password_force_numbers)
- Should password force symbols? (auth.password_force_symbols)
- Should password force mixed case? (auth.password_force_mixed_case)
